trigger:
- master

pool: 'Default'

variables:
  imageRepository: 'fiap-cloud-games'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  acrServiceConnection: 'ConexaoAzureContainerRegistry'

stages:
- stage: Build
  displayName: 'Build da Imagem Docker'
  jobs:
  - job: BuildJob
    displayName: 'Build'
    pool: 'Default'
    steps:
    - task: Docker@2
      displayName: 'Build da Imagem'
      inputs:
        command: 'build'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'

- stage: Push
  displayName: 'Push da Imagem para o Azure Container Registry'
  dependsOn: Build
  jobs:
  - job: PushJob
    displayName: 'Push'
    pool: 'Default'
    steps:
    - task: Docker@2
      displayName: 'Push da Imagem para o Azure Container Registry'
      inputs:
        command: 'push'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        tags: |
          $(tag)