# Define o gatilho (trigger) da pipeline. Ela será executada a cada commit na branch 'master'.
trigger:
- master

# Define o ambiente de execução da pipeline. Usaremos o pool 'Default' do nosso agente self-hosted.
pool: 'Default'

# Define variáveis que podem ser reutilizadas na pipeline.
variables:
  imageName: 'fiap-cloud-games' # Nome da imagem Docker que será gerada

# Define os passos (etapas) da pipeline.
steps:
- task: Docker@2
  displayName: 'Build da Imagem Docker'
  inputs:
    command: 'build'
    repository: '$(imageName)'
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(Build.BuildId)