# Define o gatilho (trigger) da pipeline. Ela será executada a cada commit na branch 'main'.
trigger:
- main

# Define o ambiente de execução da pipeline. Vamos utilizar inicialmente um self-hosted.
pool: 'Default'

# Define variáveis que podem ser reutilizadas na pipeline.
variables:
  imageName: 'fiap-cloud-games' # Nome da imagem Docker que será gerada

# Define os passos (etapas) da pipeline.
steps:
- task: Docker@2
  displayName: 'Build da Imagem Docker'
  inputs:
    command: 'build'
    repository: '$(imageName)' # Usa a variável que definimos acima
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile' # Caminho para o nosso Dockerfile
    tags: |
      $(Build.BuildId) # 'Build.BuildId' é uma tag única para cada execução